apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-deployment
  namespace: project-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        image: #project-1 node-server dockerimage
        ports:
        - containerPort: 3001