apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-server-deployment
  namespace: project-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-server
  template:
    metadata:
      labels:
        app: spring-server
    spec:
      containers:
      - name: spring-server
        image: #project-1 spring-server dockerimage
        ports:
        - containerPort: 8080